#!/usr/bin/env bash

function load_config() {
  if [[ "$2" != "NULL" ]]; then
    printf "$1 = $2\n" >> "${PGBOUNCER_DIR}/$3"
  fi
}

function load_env() {
  printf "$1" >> "${PGBOUNCER_DIR}/$2"
}


printf "\n[pgbouncer]\n" > "${PGBOUNCER_DIR}/pgbouncer.ini"
load_config "logfile" "${PGBOUNCER_DIR}/pgbouncer.log" "pgbouncer.ini"
load_config "pidfile" "${PGBOUNCER_DIR}/pgbouncer.pid" "pgbouncer.ini"
load_config "listen_addr" "${PGBOUNCER_LISTEN_ADDR:=*}" "pgbouncer.ini"
load_config "listen_port" "${PGBOUNCER_LISTEN_PORT:=5432}" "pgbouncer.ini"
load_config "unix_socket_dir" "${PGBOUNCER_UNIX_SOCKET_DIR:=/tmp}" "pgbouncer.ini"
load_config "unix_socket_mode" "${PGBOUNCER_UNIX_SOCKET_MODE:=0777}" "pgbouncer.ini"
load_config "unix_socket_group" "${PGBOUNCER_UNIX_SOCKET_GROUP:=NULL}" "pgbouncer.ini"
load_config "user" "${PGBOUNCER_USER:=NULL}" "pgbouncer.ini"
load_config "auth_file" "${PGBOUNCER_DIR}/pgbouncer_users.txt" "pgbouncer.ini"
load_config "auth_hba_file" "${PGBOUNCER_AUTH_HBA_FILE:=NULL}" "pgbouncer.ini"
load_config "auth_type" "${PGBOUNCER_AUTH_TYPE:=md5}" "pgbouncer.ini"
load_config "auth_query" "${PGBOUNCER_AUTH_QUERY:=SELECT username, passwd FROM pg_shadow WHERE username=$1}" "pgbouncer.ini"
load_config "auth_user" "${PGBOUNCER_AUTH_USER:=NULL}" "pgbouncer.ini"
load_config "pool_mode" "${PGBOUNCER_POOL_MODE:=session}" "pgbouncer.ini"
load_config "max_client_conn" "${PGBOUNCER_MAX_CLIENT_CONN:=100}" "pgbouncer.ini"
load_config "default_pool_size" "${PGBOUNCER_DEFAULT_POOL_SIZE:=20}" "pgbouncer.ini"
load_config "min_pool_size" "${PGBOUNCER_MIN_POOL_SIZE:=0}" "pgbouncer.ini"
load_config "reserve_pool_size" "${PGBOUNCER_RESERVE_POOL_SIZE:=0}" "pgbouncer.ini"
load_config "reserve_pool_timeout" "${PGBOUNCER_RESERVE_POOL_TIMEOUT:=5.0}" "pgbouncer.ini"
load_config "max_db_connections" "${PGBOUNCER_MAX_DB_CONNECTIONS:=NULL}" "pgbouncer.ini"
load_config "max_user_connections" "${PGBOUNCER_MAX_USER_CONNECTIONS:=NULL}" "pgbouncer.ini"
load_config "server_round_robin" "${PGBOUNCER_SERVER_ROUND_ROBIN:=0}" "pgbouncer.ini"
load_config "ignore_startup_parameters" "${PGBOUNCER_IGNORE_STARTUP_PARAMETERS:=NULL}" "pgbouncer.ini"
load_config "disable_pqexec" "${PGBOUNCER_DISABLE_PQEXEC:=0}" "pgbouncer.ini"
load_config "application_name_add_host" "${PGBOUNCER_APPLICATION_NAME_ADD_HOST:=0}" "pgbouncer.ini"
load_config "conffile" "${PGBOUNCER_DIR}/pgbouncer.ini" "pgbouncer.ini"
load_config "service_name" "${PGBOUNCER_SERVICE_NAME:=NULL}" "pgbouncer.ini"
load_config "job_name" "${PGBOUNCER_JOB_NAME:=NULL}" "pgbouncer.ini"
load_config "stats_period" "${PGBOUNCER_STATS_PERIOD:=60}" "pgbouncer.ini"
load_config "syslog" "${PGBOUNCER_SYSLOG:=0}" "pgbouncer.ini"
load_config "syslog_ident" "${PGBOUNCER_SYSLOG_IDENT:=pgbouncer}" "pgbouncer.ini"
load_config "syslog_facility" "${PGBOUNCER_SYSLOG_FACILITY:=daemon}" "pgbouncer.ini"
load_config "log_connections" "${PGBOUNCER_LOG_CONNECTIONS:=1}" "pgbouncer.ini"
load_config "log_disconnections" "${PGBOUNCER_LOG_DISCONNECTIONS:=1}" "pgbouncer.ini"
load_config "log_pooler_errors" "${PGBOUNCER_LOG_POOLER_ERRORS:=1}" "pgbouncer.ini"
load_config "log_stats" "${PGBOUNCER_LOG_STATS:=1}" "pgbouncer.ini"
load_config "verbose" "${PGBOUNCER_VERBOSE:=0}" "pgbouncer.ini"
load_config "admin_users" "${PGBOUNCER_ADMIN_USERS:=NULL}" "pgbouncer.ini"
load_config "stats_users" "${PGBOUNCER_STATS_USERS:=NULL}" "pgbouncer.ini"
load_config "server_reset_query" "${PGBOUNCER_SERVER_RESET_QUERY:=DISCARD ALL}" "pgbouncer.ini"
load_config "server_reset_query_always" "${PGBOUNCER_SERVER_RESET_QUERY_ALWAYS:=0}" "pgbouncer.ini"
load_config "server_check_delay" "${PGBOUNCER_SERVER_CHECK_DELAY:=30.0}" "pgbouncer.ini"
load_config "server_check_query" "${PGBOUNCER_SERVER_CHECK_QUERY:=SELECT 1;}" "pgbouncer.ini"
load_config "server_fast_close" "${PGBOUNCER_SERVER_FAST_CLOSE:=0}" "pgbouncer.ini"
load_config "server_lifetime" "${PGBOUNCER_SERVER_LIFETIME:=3600.0}" "pgbouncer.ini"
load_config "server_idle_timeout" "${PGBOUNCER_SERVER_IDLE_TIMEOUT:=600.0}" "pgbouncer.ini"
load_config "server_connect_timeout" "${PGBOUNCER_SERVER_CONNECT_TIMEOUT:=15.0}" "pgbouncer.ini"
load_config "server_login_retry" "${PGBOUNCER_SERVER_LOGIN_RETRY:=15.0}" "pgbouncer.ini"
load_config "client_login_timeout" "${PGBOUNCER_CLIENT_LOGIN_TIMEOUT:=60.0}" "pgbouncer.ini"
load_config "autodb_idle_timeout" "${PGBOUNCER_AUTODB_IDLE_TIMEOUT:=3600.0}" "pgbouncer.ini"
load_config "dns_max_ttl" "${PGBOUNCER_DNS_MAX_TTL:=15.0}" "pgbouncer.ini"
load_config "dns_nxdomain_ttl" "${PGBOUNCER_DNS_NXDOMAIN_TTL:=15.0}" "pgbouncer.ini"
load_config "dns_zone_check_period" "${PGBOUNCER_DNS_ZONE_CHECK_PERIOD:=0.0}" "pgbouncer.ini"
load_config "resolv_conf" "${PGBOUNCER_RESOLV_CONF:=NULL}" "pgbouncer.ini"
load_config "client_tls_sslmode" "${PGBOUNCER_CLIENT_TLS_SSLMODE:=disable}" "pgbouncer.ini"
load_config "client_tls_key_file" "${PGBOUNCER_CLIENT_TLS_KEY_FILE:=NULL}" "pgbouncer.ini"
load_config "client_tls_cert_file" "${PGBOUNCER_CLIENT_TLS_CERT_FILE:=NULL}" "pgbouncer.ini"
load_config "client_tls_ca_file" "${PGBOUNCER_CLIENT_TLS_CA_FILE:=NULL}" "pgbouncer.ini"
load_config "client_tls_protocols" "${PGBOUNCER_CLIENT_TLS_PROTOCOLS:=all}" "pgbouncer.ini"
load_config "client_tls_ciphers" "${PGBOUNCER_CLIENT_TLS_CIPHERS:=fast}" "pgbouncer.ini"
load_config "client_tls_ecdhcurve" "${PGBOUNCER_CLIENT_TLS_ECDHCURVE:=auto}" "pgbouncer.ini"
load_config "client_tls_dheparams" "${PGBOUNCER_CLIENT_TLS_DHEPARAMS:=auto}" "pgbouncer.ini"
load_config "server_tls_sslmode" "${PGBOUNCER_SERVER_TLS_SSLMODE:=disable}" "pgbouncer.ini"
load_config "server_tls_ca_file" "${PGBOUNCER_SERVER_TLS_CA_FILE:=NULL}" "pgbouncer.ini"
load_config "server_tls_key_file" "${PGBOUNCER_SERVER_TLS_KEY_FILE:=NULL}" "pgbouncer.ini"
load_config "server_tls_cert_file" "${PGBOUNCER_SERVER_TLS_CERT_FILE:=NULL}" "pgbouncer.ini"
load_config "server_tls_protocols" "${PGBOUNCER_SERVER_TLS_PROTOCOLS:=all}" "pgbouncer.ini"
load_config "server_tls_ciphers" "${PGBOUNCER_SERVER_TLS_CIPHERS:=fast}" "pgbouncer.ini"
load_config "query_timeout" "${PGBOUNCER_QUERY_TIMEOUT:=0.0}" "pgbouncer.ini"
load_config "query_wait_timeout" "${PGBOUNCER_QUERY_WAIT_TIMEOUT:=120}" "pgbouncer.ini"
load_config "client_idle_timeout" "${PGBOUNCER_CLIENT_IDLE_TIMEOUT:=0.0}" "pgbouncer.ini"
load_config "idle_transaction_timeout" "${PGBOUNCER_IDLE_TRANSACTION_TIMEOUT:=0.0}" "pgbouncer.ini"
load_config "suspend_timeout" "${PGBOUNCER_SUSPEND_TIMEOUT:=10}" "pgbouncer.ini"
load_config "pkt_buf" "${PGBOUNCER_PKT_BUF:=4096}" "pgbouncer.ini"
load_config "max_packet_size" "${PGBOUNCER_MAX_PACKET_SIZE:=2147483647}" "pgbouncer.ini"
load_config "listen_backlog" "${PGBOUNCER_LISTEN_BACKLOG:=128}" "pgbouncer.ini"
load_config "sbuf_loopcnt" "${PGBOUNCER_SBUF_LOOPCNT:=5}" "pgbouncer.ini"
load_config "so_reuseport" "${PGBOUNCER_SO_REUSEPORT:=0}" "pgbouncer.ini"
load_config "tcp_defer_accept" "${PGBOUNCER_TCP_DEFER_ACCEPT:=45}" "pgbouncer.ini"
load_config "tcp_socket_buffer" "${PGBOUNCER_TCP_SOCKET_BUFFER:=NULL}" "pgbouncer.ini"
load_config "tcp_keepalive" "${PGBOUNCER_TCP_KEEPALIVE:=1}" "pgbouncer.ini"
load_config "tcp_keepcnt" "${PGBOUNCER_TCP_KEEPCNT:=NULL}" "pgbouncer.ini"
load_config "tcp_keepidle" "${PGBOUNCER_TCP_KEEPIDLE:=NULL}" "pgbouncer.ini"
load_config "tcp_keepintvl" "${PGBOUNCER_TCP_KEEPINTVL:=NULL}" "pgbouncer.ini"

if [[ "${PGBOUNCER_USER_AUTH_FILE:=NULL}" != "NULL" ]]; then
  load_env "${PGBOUNCER_USER_AUTH_FILE}" "pgbouncer_users.txt"
fi

if [[ "${PGBOUNCER_DATABASES:=NULL}" != "NULL" ]]; then
  printf "\n[databases]\n" >> "${PGBOUNCER_DIR}/pgbouncer.ini"
  load_env "${PGBOUNCER_DATABASES}" "pgbouncer.ini"
fi

if [[ "${PGBOUNCER_USERS:=NULL}" != "NULL" ]]; then
  printf "\n[users]\n" >> "${PGBOUNCER_DIR}/pgbouncer.ini"
  load_env "${PGBOUNCER_USERS}" "pgbouncer.ini"
fi
