config_loader_sh_template: |
  #!/usr/bin/env bash

  function load_config() {{
    if [[ "$2" != "NULL" ]]; then
      printf "$1 = $2\n" >> "${{PGBOUNCER_DIR}}/$3"
    fi
  }}

  function load_env() {{
    printf "$1" >> "${{PGBOUNCER_DIR}}/$2"
  }}

  {load_fn_calls}

  if [[ "${{PGBOUNCER_USER_AUTH_FILE:=NULL}}" != "NULL" ]]; then
    load_env "${{PGBOUNCER_USER_AUTH_FILE}}" "pgbouncer_users.txt"
  fi

  if [[ "${{PGBOUNCER_DATABASES:=NULL}}" != "NULL" ]]; then
    printf "\n[databases]\n" >> "${{PGBOUNCER_DIR}}/pgbouncer.ini"
    load_env "${{PGBOUNCER_DATABASES}}" "pgbouncer.ini"
  fi

  if [[ "${{PGBOUNCER_USERS:=NULL}}" != "NULL" ]]; then
    printf "\n[users]\n" >> "${{PGBOUNCER_DIR}}/pgbouncer.ini"
    load_env "${{PGBOUNCER_USERS}}" "pgbouncer.ini"
  fi

config_files:
  - path: pgbouncer_configs/pgbouncer_ini.yml
    filename: pgbouncer.ini

output_dir: ../../setup