dockerfile_template: |
  FROM debian:stretch-slim

  ARG PGBOUNCER_VERSION=""
  ARG PGBOUNCER_DOWNLOAD_LINK="https://www.pgbouncer.org/downloads/files/${{PGBOUNCER_VERSION}}/pgbouncer-${{PGBOUNCER_VERSION}}.tar.gz"

  MAINTAINER Mutlu Polatcan <mutlupolatcan@gmail.com>

  ENV PGBOUNCER_CONF_DIR="/pgbouncer_conf" \
  {env_vars}

  ADD config_loader.sh ./pgbouncer_config_loader.sh
  ADD entrypoint.sh ./pgbouncer_entrypoint.sh

  RUN apt-get update && \
      apt-get -y install wget \
                         build-essential \
                         pkg-config \
                         libevent-dev \
                         libssl-dev && \
      rm -rf /var/lib/apt/lists/* && \
      wget ${{PGBOUNCER_DOWNLOAD_LINK}} && \
      tar xvzf pgbouncer-${{PGBOUNCER_VERSION}}.tar.gz && \
      pgbouncer-${{PGBOUNCER_VERSION}}/configure --prefix=/usr/local && \
      make -f pgbouncer-${{PGBOUNCER_VERSION}}/Makefile && \
      make -f pgbouncer-${{PGBOUNCER_VERSION}}/Makefile install && \
      rm -r pgbouncer-${{PGBOUNCER_VERSION}}.* && \
      mkdir -p ${{PGBOUNCER_CONF_DIR}}

  ENTRYPOINT ["./pgbouncer_entrypoint.sh"]

config_loader_sh_template: |
  #!/usr/bin/env bash

  function load_config() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "$1 = $2\n" >> "${{PGBOUNCER_CONF_DIR}}/$3"
      fi
  }}

  function load_config_with_opt() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "$1 = $3\n" >> "${{PGBOUNCER_CONF_DIR}}/$5"
      else
          printf "$1 = $4\n" >> "${{PGBOUNCER_CONF_DIR}}/$5"
      fi
  }}

  {load_fn_calls}

config_files:
  - path: pgbouncer_configs/pgbouncer_ini.yml
    filename: pgbouncer.ini

output_dir: ../../setup