dockerfile_template: |
  FROM debian:stretch-slim

  ARG PGBOUNCER_VERSION=""
  ARG PGBOUNCER_DOWNLOAD_LINK="https://www.pgbouncer.org/downloads/files/${{PGBOUNCER_VERSION}}/pgbouncer-${{PGBOUNCER_VERSION}}.tar.gz"

  MAINTAINER Mutlu Polatcan <mutlupolatcan@gmail.com>

  ENV PGBOUNCER_DIR="/pgbouncer" \
      PGBOUNCER_DATABASES="NULL" \
      PGBOUNCER_USERS="NULL" \
      PGBOUNCER_USER_AUTH_FILE="NULL" \
  {env_vars}

  ADD config_loader.sh ./pgbouncer_config_loader.sh
  ADD entrypoint.sh ./pgbouncer_entrypoint.sh

  RUN addgroup pgbouncer && adduser --disabled-password --gecos "" --ingroup pgbouncer pgbouncer && \
      apt-get update && \
      apt-get -y install wget \
                         build-essential \
                         pkg-config \
                         libevent-dev \
                         libssl-dev && \
      rm -rf /var/lib/apt/lists/* && \
      wget ${{PGBOUNCER_DOWNLOAD_LINK}} && \
      tar xvzf pgbouncer-${{PGBOUNCER_VERSION}}.tar.gz && \
      cd pgbouncer-${{PGBOUNCER_VERSION}} && \
      ./configure --prefix=/usr/local && make && make install && \
      cd ../ && \
      rm -r pgbouncer-${{PGBOUNCER_VERSION}}.* && \
      mkdir -p ${{PGBOUNCER_DIR}} && \
      chmod +x pgbouncer_config_loader.sh pgbouncer_entrypoint.sh && \
      chown -R pgbouncer:pgbouncer ${{PGBOUNCER_DIR}} pgbouncer_config_loader.sh pgbouncer_entrypoint.sh

  USER pgbouncer
  ENTRYPOINT ["./pgbouncer_entrypoint.sh"]

config_loader_sh_template: |
  #!/usr/bin/env bash

  function load_config() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "$1 = $2\n" >> "${{PGBOUNCER_DIR}}/$3"
      fi
  }}

  function load_config_with_opt() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "$1 = $3\n" >> "${{PGBOUNCER_DIR}}/$5"
      else
          printf "$1 = $4\n" >> "${{PGBOUNCER_DIR}}/$5"
      fi
  }}

  function load_env() {{
      printf "$1" >> "${{PGBOUNCER_DIR}}/$2"
  }}

  {load_fn_calls}

  if [[ "${{PGBOUNCER_USER_AUTH_FILE}}" != "NULL" ]]; then
    load_env "${{PGBOUNCER_USER_AUTH_FILE}}" "pgbouncer_users.txt"
  fi

  if [[ "${{PGBOUNCER_DATABASES}}" != "NULL" ]]; then
    printf "\n[databases]\n" >> "${{PGBOUNCER_DIR}}/pgbouncer.ini"
    load_env "${{PGBOUNCER_DATABASES}}" "pgbouncer.ini"
  fi

  if [[ "${{PGBOUNCER_USERS}}" != "NULL" ]]; then
    printf "\n[users]\n" >> "${{PGBOUNCER_DIR}}/pgbouncer.ini"
    load_env "${{PGBOUNCER_DATABASES}}" "pgbouncer.ini"
  fi

config_files:
  - path: pgbouncer_configs/pgbouncer_ini.yml
    filename: pgbouncer.ini

output_dir: ../../setup